name = "GenLinAlgProblems"
uuid = "3c0f76d2-298f-40a4-82ea-fb4356fbbd2d"
authors = ["ea42gh <ea42_github@mail.com> and contributors"]
version = "0.4.0"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
AngleBetweenVectors = "ec570357-d46e-52ed-9726-18773498274d"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
Hadamard = "4a05ff16-5f95-55f4-bb53-bb3f467c689a"
HypertextLiteral = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
IOCapture = "b5f81e59-6552-4d32-b1f0-c071b021bf89"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
RowEchelon = "af85af4c-bcd5-5d23-b03a-a909639aa875"
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"
SymPy = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"
ToeplitzMatrices = "c751599d-da0a-543b-9d20-d0a503d91d24"

[compat]
DSP = "0.7.10"
FFTW = "1.8.0"
GenericLinearAlgebra = "0.3.14"
HypertextLiteral = "0.9.5"
IOCapture = "0.2.5"
PlotlyBase = "0.8.19"
PyPlot = "2.11.5"
ToeplitzMatrices = "0.8.4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
